### ISSUE TITLE
Symfony 3.4 support

### ISSUE THREAD

**Issue by edhgoose** [pkruithof/markdownify-bundle#7]
First - just wanted to say thanks for this bundle. We've been using it in production for a very long time now and it's great.

We're looking to upgrade to Symfony 3.4 and we're getting this error:

Invalid service "markdownify": the value of argument "linksAfterEachParagraph" of method "Markdownify\ConverterExtra::__construct()" must be null, an instance of Symfony\Component\DependencyInjection\Reference or an instance of Symfony\Component\DependencyInjection\Definition, integer given.

I believe we need to make a change to the service config:

      linksAfterEachParagraph: '%markdownify.link_position%'

becomes:

      $linksAfterEachParagraph: '%markdownify.link_position%'

or:

      0: '%markdownify.link_position%'

(Where 0 is the argument position)

**Comment by pkruithof** [comment]
Positional arguments seem fine. I put the named arguments there originally for documentation. But with the README and bundle configuration, it's documented well enough.

I'd just make a plain list now:

```yaml
arguments:
  - '%markdownify.link_position%'
```

Can you make a PR for this?

**Comment by edhgoose** [comment]
Sure, here you go: https://github.com/pkruithof/markdownify-bundle/pull/8
